name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js with pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2 # https://github.com/silverhand-io/actions-node-pnpm-run-steps/blob/master/action.yml
        with:
          node-version: 18 # 18 is the latest LTS version
          pnpm-version: 7 # 7 is the latest major version, 7.29.0 is latest at the time of writing
          registry-url: https://registry.npmjs.org # optional, defaults to https://registry.npmjs.org
          run-install: false # sync package.json and install deps manually in the next steps

      - name: Sync package.json and install deps
        run: pnpm package:sync --silent && pnpm ci

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm -r --parallel test:coverage