name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  
  build-node:
    name: "Build Node.js"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
    
      - name: "Clean install dependencies"
        run: npm ci

      - name: "Run npm build"
        run: npm run build

      # Uncomment this step when we have tests
      # - name: "Execute tests"
      #   run: npm test

  build-docker:
    # Build custom staging Docker image for LogTo
    name: "LogTo Docker image - Staging"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cheqd/creds-auth

    steps:
      - uses: actions/checkout@v4

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
            registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          load: true
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=logto-staging.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min
      
      - name: Upload Docker test image
        uses: actions/upload-artifact@v4
        with:
          name: logto-staging
          path: logto-staging.tar
