name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'pnpm' # running pnpm install will use the cache automatically

      - name: Sync package.json and install deps
        run: pnpm package:sync --silent && pnpm ci

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm -r --parallel test:coverage