name: "Build Nginx"
on: 
  push:
    paths:
      - nginx-sidecar/**
defaults:
  run:
    shell: bash

jobs:
  push-nginx-staging:
    name: "Staging Deploy"
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }}
    env: 
      IMAGE_NAME: registry.digitalocean.com/cheqd/nginx

    steps:
      - uses: actions/checkout@v3

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nginx-sidecar/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=min  

      - name: Push staging image to DOCR
        run: docker image push --all-tags ${{ env.IMAGE_NAME }}

  push-nginx-production:
    name: "Production Deploy"
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    env: 
      IMAGE_NAME: registry.digitalocean.com/cheqd/nginx

    steps:
      - uses: actions/checkout@v3

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nginx-sidecar/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=min  

      - name: Push staging image to DOCR
        run: docker image push --all-tags ${{ env.IMAGE_NAME }}