name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  build-docker:
    # Doing a build at this stage will create reusable cache layers for release workflow
    name: "Custom LogTo Docker image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/logto.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min
          secrets: |
            "CA_CERT=${{ secrets.CA_CERT }}""
      
      - name: Upload Docker test image
        uses: actions/upload-artifact@v3
        with:
          name: logto.tar
          path: /tmp/logto.tar
